/*
********************************************************************
* USB Device Driver for Irix 6.5                                   *
*                                                                  *
* Programmed by BSDero                                             *
* bsdero at gmail dot com                                          *
* 2011/2012                                                        *
*                                                                  *
*                                                                  *
* File: config.h                                                   *
* Description: Build values defines                                *
*                                                                  *
*                                                                  *
********************************************************************
*******************************************************************************************************
* FIXLIST (latest at top)                                                                             *
*-----------------------------------------------------------------------------------------------------*
* Author      MM-DD-YYYY     Description                                                              *
*-----------------------------------------------------------------------------------------------------*
* BSDero      01-05-2012     -Initial version                                                         *
*                                                                                                     *
*******************************************************************************************************


WARNING!!!!

DO NOT EDIT THIS FILE, IS AUTOGENERATED!!

*/


#define USBCORE_DRV_SHORT_NAME                "USBCORE"
#define USBCORE_DRV_LONG_NAME                 "USB stack and host controller driver for SGI IRIX 6.5 <bsdero at gmail dot org>"
#define USBCORE_DRV_VERSION                   "0.0.1.5"
#define USBCORE_DRV_SHORT_VERSION             "0015"
#define USBCORE_DRV_SEQ                       "00131105182012"
#define USBCORE_DRV_BUILD_DATE                    "Fri May 18 00:13:11 2012"


